name: terraform
on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
          terraform_wrapper: false

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - uses: lablabs/setup-terraform-docs@v1
        name: Setup Terraform docs
        with:
          terraform_docs_version: v0.4.1

      - name: pre-commit
        uses: pre-commit/action@v2.0.3
